{% set name = "gsutil" %}
{% set version = "4.63" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0531e1cef641bcb348a488ddc15c1612587269fc3bd366a0d1e362e2d4891864

build:
  number: 0
  noarch: python
  entry_points:
    - gsutil = gslib.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - argcomplete >=1.9.4
    - crcmod >=1.7
    - fasteners >=0.14.1
    - gcs-oauth2-boto-plugin >=2.5
    - google-apitools >=0.5.30
    - google-reauth >=0.1.0
    - httplib2 >=0.11.3
    - mock =2.0.0
    - monotonic >=1.4
    - oauth2client =4.1.3
    - pyopenssl >=0.13
    - python <4.0
    - retry_decorator >=1.0.0
    - six >=1.12.0
    - socksipy-branch =1.01
  run_constrained:
    - google-cloud-sdk <0a

test:
  imports:
    - gslib
    - gslib.addlhelp
  commands:
    - pip check
    - gsutil version
  requires:
    - pip

about:
  home: https://pypi.org/project/gsutil/
  summary: A command line tool for interacting with cloud storage services.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
